import "@styles/globals.css";
import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@lib/utils";
import { ThemeProvider } from "@components/theme-provider";
import ConsoleFilter from "@components/console-filter";
import Navbar from "@components/Navbar";

// ---------------------------------------------------------------------------
// Development‑only console filter to silence the React warning about a
// <script> tag rendered inside a component (generated by next‑themes).
// The warning is harmless – the script runs correctly – but it clutters the
// console. The filter runs only in development and ignores any warning that
// contains the specific message.
// ---------------------------------------------------------------------------
if (process.env.NODE_ENV === "development") {
  const originalWarn = console.warn;
  console.warn = (msg: unknown, ...rest: unknown[]) => {
    if (
      typeof msg === "string" &&
      msg.includes("script tag while rendering")
    ) {
      return; // swallow this specific warning
    }
    originalWarn(msg, ...rest);
  };
}

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Vivek Kumar",
  description: "Generated by create next app",
  
    icons: "/favicon.ico",
  
    metadataBase: new URL("https://l-fifa-l.github.io"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <html lang="en" suppressHydrationWarning={true}>
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      
      <body
        className={cn(
          "min-h-full bg-background font-sans antialiased overflow-y-scroll no-scrollbar",
          fontSans.variable
        )}
      >
        <ConsoleFilter>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Analytics />
          </ThemeProvider>
        </ConsoleFilter>
      </body>
    </html>
  )
}