"use client";

import { useEffect } from "react";

/**
 * ConsoleFilter suppresses the specific React warning about a <script> tag
 * rendered inside a component (generated by next‑themes). The warning is
 * harmless, but it clutters the console during development.
 *
 * The filter is applied once on mount and restored when the component
 * unmounts.
 */
export default function ConsoleFilter({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    const originalWarn = console.warn;
    console.warn = (msg: unknown, ...rest: unknown[]) => {
      if (
        typeof msg === "string" &&
        msg.includes("script tag while rendering")
      ) {
        // swallow this specific warning
        return;
      }
      originalWarn(msg, ...rest);
    };
    return () => {
      // restore original console.warn when the component unmounts
      console.warn = originalWarn;
    };
  }, []);

  return <>{children}</>;
}
